name: Converge website
on:
  push:
    branches: [master]

jobs:
  converge:
    name: Converge site to Production
    runs-on: tfprod-werf
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: werf/actions/converge@v1.2
      env:
        WERF_SET_DOCKER_CONFIG_JSON: "true"
      with:
        version: v1.2.29
